const dadosFilmes = [
    // --- TIER S+ ---
    {tier: "S+", titulo: "Snow White and the Seven Dwarfs", ano: 1937, genero: "Animação"},
    {tier: "S+", titulo: "Cinderella", ano: 1950, genero: "Animação"},
    {tier: "S+", titulo: "Sleeping Beauty", ano: 1959, genero: "Animação"},
    {tier: "S+", titulo: "Rambo: First Blood", ano: 1982, genero: "Ação"},
    {tier: "S+", titulo: "Predator", ano: 1987, genero: "Ficção Científica"},
    {tier: "S+", titulo: "The Little Mermaid", ano: 1989, genero: "Animação"},
    {tier: "S+", titulo: "Beauty and the Beast", ano: 1991, genero: "Animação"},
    {tier: "S+", titulo: "The Lion King", ano: 1994, genero: "Animação"},
    {tier: "S+", titulo: "Toy Story", ano: 1995, genero: "Animação"},
    {tier: "S+", titulo: "A Bug's Life", ano: 1998, genero: "Animação"},
    {tier: "S+", titulo: "Tarzan", ano: 1999, genero: "Animação"},
    {tier: "S+", titulo: "Monsters, Inc.", ano: 2001, genero: "Animação"},
    {tier: "S+", titulo: "Shrek", ano: 2001, genero: "Animação"},
    {tier: "S+", titulo: "Ice Age", ano: 2002, genero: "Animação"},
    {tier: "S+", titulo: "Spirit: Stallion of the Cimarron", ano: 2002, genero: "Animação"},
    {tier: "S+", titulo: "Spider-Man", ano: 2002, genero: "Heróis"},
    {tier: "S+", titulo: "Finding Nemo", ano: 2003, genero: "Animação"},
    {tier: "S+", titulo: "Hulk", ano: 2003, genero: "Heróis"},
    {tier: "S+", titulo: "Van Helsing", ano: 2004, genero: "Terror"},
    {tier: "S+", titulo: "Spider-Man 2", ano: 2004, genero: "Heróis"},
    {tier: "S+", titulo: "Shrek 2", ano: 2004, genero: "Animação"},
    {tier: "S+", titulo: "The Day After Tomorrow", ano: 2004, genero: "Drama"},
    {tier: "S+", titulo: "Madagascar", ano: 2005, genero: "Animação"},
    {tier: "S+", titulo: "Cars", ano: 2006, genero: "Animação"},
    {tier: "S+", titulo: "Final Destination 3", ano: 2006, genero: "Terror"},
    {tier: "S+", titulo: "Ice Age: The Meltdown", ano: 2006, genero: "Animação"},
    {tier: "S+", titulo: "Open Season", ano: 2006, genero: "Animação"},
    {tier: "S+", titulo: "300", ano: 2006, genero: "Aventura"},
    {tier: "S+", titulo: "I Am Legend", ano: 2007, genero: "Ficção Científica"},
    {tier: "S+", titulo: "Mr. Bean's Holiday", ano: 2007, genero: "Comédia"},
    {tier: "S+", titulo: "Ratatouille", ano: 2007, genero: "Animação"},
    {tier: "S+", titulo: "Bolt", ano: 2008, genero: "Animação"},
    {tier: "S+", titulo: "Horton", ano: 2008, genero: "Animação"},
    {tier: "S+", titulo: "Kung Fu Panda", ano: 2008, genero: "Animação"},
    {tier: "S+", titulo: "Madagascar 2", ano: 2008, genero: "Animação"},
    {tier: "S+", titulo: "WALL-E", ano: 2008, genero: "Animação"},
    {tier: "S+", titulo: "Iron Man", ano: 2008, genero: "Heróis"},
    {tier: "S+", titulo: "The Incredible Hulk", ano: 2008, genero: "Heróis"},
    {tier: "S+", titulo: "Death Race", ano: 2008, genero: "Ação"},
    {tier: "S+", titulo: "Taken", ano: 2008, genero: "Ação"},
    {tier: "S+", titulo: "10,000 BC", ano: 2008, genero: "Aventura"},
    {tier: "S+", titulo: "Ice Age: Dawn of the Dinosaurs", ano: 2009, genero: "Animação"},
    {tier: "S+", titulo: "Up", ano: 2009, genero: "Animação"},
    {tier: "S+", titulo: "Avatar", ano: 2009, genero: "Aventura"},
    {tier: "S+", titulo: "Despicable Me", ano: 2010, genero: "Animação"},
    {tier: "S+", titulo: "How to Train Your Dragon", ano: 2010, genero: "Animação"},
    {tier: "S+", titulo: "Toy Story 3", ano: 2010, genero: "Animação"},
    {tier: "S+", titulo: "Cars 2", ano: 2011, genero: "Animação"},
    {tier: "S+", titulo: "Rango", ano: 2011, genero: "Animação"},
    {tier: "S+", titulo: "Kung Fu Panda 2", ano: 2011, genero: "Animação"},
    {tier: "S+", titulo: "Brave", ano: 2012, genero: "Animação"},
    {tier: "S+", titulo: "Hotel Transylvania", ano: 2012, genero: "Animação"},
    {tier: "S+", titulo: "Ice Age: Continental Drift", ano: 2012, genero: "Animação"},
    {tier: "S+", titulo: "Madagascar 3", ano: 2012, genero: "Animação"},
    {tier: "S+", titulo: "Ted", ano: 2012, genero: "Comédia"},
    {tier: "S+", titulo: "The Amazing Spider-Man", ano: 2012, genero: "Heróis"},
    {tier: "S+", titulo: "The Avengers", ano: 2012, genero: "Heróis"},
    {tier: "S+", titulo: "A Vida de Pi", ano: 2012, genero: "Drama"},
    {tier: "S+", titulo: "Despicable Me 2", ano: 2013, genero: "Animação"},
    {tier: "S+", titulo: "Epic", ano: 2013, genero: "Animação"},
    {tier: "S+", titulo: "Frozen", ano: 2013, genero: "Animação"},
    {tier: "S+", titulo: "Monsters University", ano: 2013, genero: "Animação"},
    {tier: "S+", titulo: "The Starving Games", ano: 2013, genero: "Comédia"},
    {tier: "S+", titulo: "World War Z", ano: 2013, genero: "Ficção Científica"},
    {tier: "S+", titulo: "Turbo", ano: 2013, genero: "Animação"},
    {tier: "S+", titulo: "The Amazing Spider-Man 2 ", ano: 2014, genero: "Heróis"},
    {tier: "S+", titulo: "Hercules", ano: 2014, genero: "Aventura"},
    {tier: "S+", titulo: "How to Train Your Dragon 2", ano: 2014, genero: "Animação"},
    {tier: "S+", titulo: "The Equalizer", ano: 2014, genero: "Ação"},
    {tier: "S+", titulo: "Non-Stop", ano: 2014, genero: "Ação"},
    {tier: "S+", titulo: "The Fault in Our Stars", ano: 2014, genero: "Drama"},
    {tier: "S+", titulo: "Hotel Transylvania 2", ano: 2015, genero: "Animação"},
    {tier: "S+", titulo: "Inside Out", ano: 2015, genero: "Animação"},
    {tier: "S+", titulo: "Minions", ano: 2015, genero: "Animação"},
    {tier: "S+", titulo: "Ted 2", ano: 2015, genero: "Comédia"},
    {tier: "S+", titulo: "Avengers: Age of Ultron", ano: 2015, genero: "Heróis"},
    {tier: "S+", titulo: "Ant-Man", ano: 2015, genero: "Heróis"},
    {tier: "S+", titulo: "Mad Max: Fury Road", ano: 2015, genero: "Ação"},
    {tier: "S+", titulo: "The Revenant: O Renascido", ano: 2015, genero: "Aventura"},
    {tier: "S+", titulo: "Pixels", ano: 2015, genero: "Ação"},
    {tier: "S+", titulo: "The Angry Birds Movie", ano: 2016, genero: "Animação"},
    {tier: "S+", titulo: "Train to Busan", ano: 2016, genero: "Ficção Científica"},
    {tier: "S+", titulo: "Zootopia", ano: 2016, genero: "Animação"},
    {tier: "S+", titulo: "Doctor Strange", ano: 2016, genero: "Heróis"},
    {tier: "S+", titulo: "Deadpool", ano: 2016, genero: "Heróis"},
    {tier: "S+", titulo: "Central Intelligence", ano: 2016, genero: "Comédia"},
    {tier: "S+", titulo: "Kung Fu Panda 3", ano: 2016, genero: "Animação"},
    {tier: "S+", titulo: "A Silent Voice", ano: 2016, genero: "Anime"},
    {tier: "S+", titulo: "Alien: Covenant", ano: 2017, genero: "Terror / Ficção Científica"},
    {tier: "S+", titulo: "Despicable Me 3", ano: 2017, genero: "Animação"},
    {tier: "S+", titulo: "Get Out", ano: 2017, genero: "Terror"},
    {tier: "S+", titulo: "It", ano: 2017, genero: "Terror"},
    {tier: "S+", titulo: "Spider-Man: Homecoming", ano: 2017, genero: "Heróis"},
    {tier: "S+", titulo: "Thor: Ragnarok", ano: 2017, genero: "Heróis"},
    {tier: "S+", titulo: "A Quiet Place", ano: 2018, genero: "Terror / Ficção Científica"},
    {tier: "S+", titulo: "The Meg", ano: 2018, genero: "Ficção Científica"},
    {tier: "S+", titulo: "Avengers: Infinity War", ano: 2018, genero: "Heróis"},
    {tier: "S+", titulo: "Ant-Man and the Wasp", ano: 2018, genero: "Heróis"},
    {tier: "S+", titulo: "Deadpool 2", ano: 2018, genero: "Heróis"},
    {tier: "S+", titulo: "Rampage", ano: 2018, genero: "Ação / Ficção Científica"},
    {tier: "S+", titulo: "Venom", ano: 2018, genero: "Heróis"},
    {tier: "S+", titulo: "Dragon Ball Super: Broly", ano: 2018, genero: "Anime"},
    {tier: "S+", titulo: "Frozen II", ano: 2019, genero: "Animação"},
    {tier: "S+", titulo: "It Chapter Two", ano: 2019, genero: "Terror"},
    {tier: "S+", titulo: "The Angry Birds Movie 2", ano: 2019, genero: "Animação"},
    {tier: "S+", titulo: "Us", ano: 2019, genero: "Terror"},
    {tier: "S+", titulo: "Avengers: Endgame", ano: 2019, genero: "Heróis"},
    {tier: "S+", titulo: "One Piece Stampede", ano: 2019, genero: "Anime"},
    {tier: "S+", titulo: "A Quiet Place Part II", ano: 2020, genero: "Terror / Ficção Científica"},
    {tier: "S+", titulo: "Shang-Chi and the Legend of the Ten Rings", ano: 2021, genero: "Heróis"},
    {tier: "S+", titulo: "Venom: Let There Be Carnage", ano: 2021, genero: "Heróis"},
    {tier: "S+", titulo: "Nobody", ano: 2021, genero: "Ação"},
    {tier: "S+", titulo: "Minions: The Rise of Gru", ano: 2022, genero: "Animação"},
    {tier: "S+", titulo: "Puss in Boots: The Last Wish", ano: 2022, genero: "Animação"},
    {tier: "S+", titulo: "The Bad Guys", ano: 2022, genero: "Animação"},
    {tier: "S+", titulo: "The Sea Beast", ano: 2022, genero: "Animação"},
    {tier: "S+", titulo: "Doctor Strange in the Multiverse of Madness", ano: 2022, genero: "Heróis"},
    {tier: "S+", titulo: "Avatar: The Way of Water", ano: 2022, genero: "Aventura"},
    {tier: "S+", titulo: "Elemental", ano: 2023, genero: "Animação"},
    {tier: "S+", titulo: "A Quiet Place: Day One", ano: 2024, genero: "Terror / Ficção Científica"},
    {tier: "S+", titulo: "Alien: Romulus", ano: 2024, genero: "Terror / Ficção Científica"},
    {tier: "S+", titulo: "The Wild Robot", ano: 2024, genero: "Animação"},
    {tier: "S+", titulo: "The Beekeeper", ano: 2024, genero: "Ação"},
    {tier: "S+", titulo: "The Lord of the Rings: The War of the Rohirrim", ano: 2024, genero: "Aventura"},
    {tier: "S+", titulo: "Inside Out 2", ano: 2024, genero: "Animação"},
    {tier: "S+", titulo: "Avatar: Fire and Ash", ano: 2025, genero: "Aventura"},
    {tier: "S+", titulo: "Spider-Man: Brand New Day", ano: 2026, genero: "Heróis"},
    {tier: "S+", titulo: "Goat", ano: 2026, genero: "Animação"},
    {tier: "S+", titulo: "Rise of the Planet of the Apes", ano: 2011, genero: "Ação"},
    {tier: "S+", titulo: "Dawn of the Planet of the Apes", ano: 2014, genero: "Ação"},
    {tier: "S+", titulo: "Jurassic World", ano: 2015, genero: "Ação / Ficção Científica"},
    {tier: "S+", titulo: "Jurassic Park 3", ano: 2001, genero: "Ação / Ficção Científica"},
    {tier: "S+", titulo: "Fast & Furious", ano: 2001, genero: "Ação"},
    {tier: "S+", titulo: "Fast & Furious 3", ano: 2006, genero: "Ação"},
    {tier: "S+", titulo: "Fast & Furious 7", ano: 2015, genero: "Ação"},

    // --- TIER S ---
    {tier: "S", titulo: "Home Alone", ano: 1990, genero: "Comédia"},
    {tier: "S", titulo: "Brother Bear", ano: 2003, genero: "Animação"},
    {tier: "S", titulo: "Final Destination 2", ano: 2003, genero: "Terror"},
    {tier: "S", titulo: "Alien vs. Predator", ano: 2004, genero: "Terror / Ficção Científica"},
    {tier: "S", titulo: "Surf's Up", ano: 2007, genero: "Animação"},
    {tier: "S", titulo: "Cloverfield", ano: 2008, genero: "Terror / Ficção Científica"},
    {tier: "S", titulo: "The Dark Knight", ano: 2008, genero: "Heróis"},
    {tier: "S", titulo: "Cloudy with a Chance of Meatballs", ano: 2009, genero: "Animação"},
    {tier: "S", titulo: "One Piece Film: Strong World", ano: 2009, genero: "Anime"},
    {tier: "S", titulo: "Megamind", ano: 2010, genero: "Animação"},
    {tier: "S", titulo: "Tangled", ano: 2010, genero: "Animação"},
    {tier: "S", titulo: "Iron Man 2", ano: 2010, genero: "Heróis"},
    {tier: "S", titulo: "Rio", ano: 2011, genero: "Animação"},
    {tier: "S", titulo: "The Grey", ano: 2011, genero: "Drama"},
    {tier: "S", titulo: "Rise of the Guardians", ano: 2012, genero: "Animação"},
    {tier: "S", titulo: "Wreck-It Ralph", ano: 2012, genero: "Animação"},
    {tier: "S", titulo: "Cloudy with a Chance of Meatballs 2", ano: 2013, genero: "Animação"},
    {tier: "S", titulo: "Homefront", ano: 2013, genero: "Ação"},
    {tier: "S", titulo: "Rio 2", ano: 2014, genero: "Animação"},
    {tier: "S", titulo: "John Wick", ano: 2014, genero: "Ação"},
    {tier: "S", titulo: "In the Heart ao Sea", ano: 2015, genero: "Drama"},
    {tier: "S", titulo: "One Piece Film: Gold", ano: 2016, genero: "Anime"},
    {tier: "S", titulo: "Cars 3", ano: 2017, genero: "Animação"},
    {tier: "S", titulo: "Hotel Transylvania 3: Summer Vacation", ano: 2018, genero: "Animação"},
    {tier: "S", titulo: "Ralph Breaks the Internet", ano: 2018, genero: "Animação"},
    {tier: "S", titulo: "Spider-Man: Into the Spider-Verse", ano: 2018, genero: "Animação"},
    {tier: "S", titulo: "Alpha", ano: 2018, genero: "Aventura"},
    {tier: "S", titulo: "The Lion King (2019)", ano: 2019, genero: "Aventura"},
    {tier: "S", titulo: "Toy Story 4", ano: 2019, genero: "Animação"},
    {tier: "S", titulo: "My Hero Academia: Heroes Rising", ano: 2019, genero: "Anime"},
    {tier: "S", titulo: "Extraction", ano: 2020, genero: "Ação"},
    {tier: "S", titulo: "Wrath of Man", ano: 2021, genero: "Ação"},
    {tier: "S", titulo: "Man vs. Bee", ano: 2022, genero: "Comédia"},
    {tier: "S", titulo: "Smile", ano: 2022, genero: "Terror"},
    {tier: "S", titulo: "Talk to Me", ano: 2022, genero: "Terror"},
    {tier: "S", titulo: "One Piece Film: Red", ano: 2022, genero: "Anime"},
    {tier: "S", titulo: "Migration", ano: 2023, genero: "Animação"},
    {tier: "S", titulo: "The Meg 2: The Trench", ano: 2023, genero: "Ficção Científica"},
    {tier: "S", titulo: "Ant-Man and the Wasp: Quantumania", ano: 2023, genero: "Heróis"},
    {tier: "S", titulo: "Extraction 2", ano: 2023, genero: "Ação"},
    {tier: "S", titulo: "Spy × Family Code: White", ano: 2023, genero: "Anime"},
    {tier: "S", titulo: "Black Clover: Sword of the Wizard King", ano: 2023, genero: "Anime"},
    {tier: "S", titulo: "Venom: The Last Dance", ano: 2024, genero: "Heróis"},
    {tier: "S", titulo: "Mufasa: The Lion King", ano: 2024, genero: "Drama"},
    {tier: "S", titulo: "Damsel", ano: 2024, genero: "Aventura"},
    {tier: "S", titulo: "Working Man", ano: 2025, genero: "Ação"},
    {tier: "S", titulo: "Demon Slayer: Infinity Castle", ano: 2025, genero: "Anime"},
    {tier: "S", titulo: "How to Train Your Dragon Live Action", ano: 2025, genero: "Aventura"},
    {tier: "S", titulo: "War for the Planet of the Apes", ano: 2017, genero: "Ação"},
    {tier: "S", titulo: "Jurassic World Dominion", ano: 2022, genero: "Ação / Ficção Científica"},
    {tier: "S", titulo: "Pirates of the Caribbean: Dead Men Tell No Tales", ano: 2017, genero: "Aventura"},
    {tier: "S", titulo: "Fast & Furious 2", ano: 2003, genero: "Ação"},
    {tier: "S", titulo: "Fast & Furious 4", ano: 2009, genero: "Ação"},
    {tier: "S", titulo: "Fast & Furious 8", ano: 2017, genero: "Ação"},
    {tier: "S", titulo: "Fast & Furious Presents: Hobbs & Shaw", ano: 2019, genero: "Ação"},
    {tier: "S", titulo: "The Super Mario Bros", ano: 2023, genero: "Animação"},
    {tier: "S", titulo: "The Super Mario Galaxy", ano: 2026, genero: "Animação"},

    // --- TIER A ---
    {tier: "A", titulo: "The Jungle Book", ano: 1967, genero: "Animação"},
    {tier: "A", titulo: "The Thing", ano: 1982, genero: "Terror / Ficção Científica"},
    {tier: "A", titulo: "Rambo: First Blood Part II", ano: 1985, genero: "Ação"},
    {tier: "A", titulo: "Chucky", ano: 1988, genero: "Terror"},
    {tier: "A", titulo: "Aladdin", ano: 1992, genero: "Animação"},
    {tier: "A", titulo: "Home Alone 2: Lost in New York", ano: 1992, genero: "Comédia"},
    {tier: "A", titulo: "Final Destination", ano: 2000, genero: "Terror"},
    {tier: "A", titulo: "The Scorpion King", ano: 2002, genero: "Aventura"},
    {tier: "A", titulo: "Johnny English", ano: 2003, genero: "Comédia"},
    {tier: "A", titulo: "Shark Tale", ano: 2004, genero: "Animação"},
    {tier: "A", titulo: "White Chicks", ano: 2004, genero: "Comédia"},
    {tier: "A", titulo: "Over the Hedge", ano: 2006, genero: "Animação"},
    {tier: "A", titulo: "Spider-Man 3", ano: 2007, genero: "Heróis"},
    {tier: "A", titulo: "2012", ano: 2009, genero: "Drama"},
    {tier: "A", titulo: "Johnny English Reborn", ano: 2011, genero: "Comédia"},
    {tier: "A", titulo: "Puss in Boots", ano: 2011, genero: "Animação"},
    {tier: "A", titulo: "Thor", ano: 2011, genero: "Heróis"},
    {tier: "A", titulo: "The Lorax", ano: 2012, genero: "Animação"},
    {tier: "A", titulo: "One Piece Film: Z", ano: 2012, genero: "Anime"},
    {tier: "A", titulo: "Iron Man 3", ano: 2013, genero: "Heróis"},
    {tier: "A", titulo: "Dragon Ball Z: Battle of Gods", ano: 2013, genero: "Anime"},
    {tier: "A", titulo: "Captain America: The Winter Soldier", ano: 2014, genero: "Heróis"},
    {tier: "A", titulo: "San Andreas", ano: 2015, genero: "Ação"},
    {tier: "A", titulo: "Finding Dory", ano: 2016, genero: "Animação"},
    {tier: "A", titulo: "Moana", ano: 2016, genero: "Animação"},
    {tier: "A", titulo: "The Secret Life of Pets", ano: 2016, genero: "Animação"},
    {tier: "A", titulo: "Captain America: Civil War", ano: 2016, genero: "Heróis"},
    {tier: "A", titulo: "Ferdinand", ano: 2017, genero: "Animação"},
    {tier: "A", titulo: "The Emoji", ano: 2017, genero: "Animação"},
    {tier: "A", titulo: "Jumanji: Welcome to the Jungle", ano: 2017, genero: "Ação"},
    {tier: "A", titulo: "Sword Art Online: Ordinal Scale", ano: 2017, genero: "Anime"},
    {tier: "A", titulo: "Johnny English Strikes Again", ano: 2018, genero: "Comédia"},
    {tier: "A", titulo: "The Nun", ano: 2018, genero: "Terror"},
    {tier: "A", titulo: "Spider-Man: Far From Home", ano: 2019, genero: "Heróis"},
    {tier: "A", titulo: "Jumanji: The Next Level", ano: 2019, genero: "Ação"},
    {tier: "A", titulo: "Rambo: Last Blood", ano: 2019, genero: "Ação"},
    {tier: "A", titulo: "How to Train Your Dragon 3", ano: 2019, genero: "Animação"},
    {tier: "A", titulo: "The Plataform", ano: 2019, genero: "Terror"},
    {tier: "A", titulo: "Spider-Man: No Way Home", ano: 2021, genero: "Heróis"},
    {tier: "A", titulo: "Red Notice ", ano: 2021, genero: "Ação"},
    {tier: "A", titulo: "Jujutsu Kaisen 0", ano: 2021, genero: "Anime"},
    {tier: "A", titulo: "Turning Red", ano: 2022, genero: "Animação"},
    {tier: "A", titulo: "Samaritan", ano: 2022, genero: "Ação"},
    {tier: "A", titulo: "The Nun II", ano: 2023, genero: "Terror"},
    {tier: "A", titulo: "Wonka", ano: 2023, genero: "Drama"},
    {tier: "A", titulo: "Despicable Me 4", ano: 2024, genero: "Animação"},
    {tier: "A", titulo: "Sonic 3", ano: 2024, genero: "Ação"},
    {tier: "A", titulo: "Godzilla x Kong: The New Empire", ano: 2024, genero: "Ação / Ficção Científica"},
    {tier: "A", titulo: "Kingdom of the Planet of the Apes", ano: 2024, genero: "Ação"},
    {tier: "A", titulo: "Elevation", ano: 2024, genero: "Ação"},
    {tier: "A", titulo: "Caramelo", ano: 2025, genero: "Drama"},
    {tier: "A", titulo: "Tron: Ares", ano: 2025, genero: "Ação"},
    {tier: "A", titulo: "The Gorge", ano: 2025, genero: "Ação / Ficção Científica"},
    {tier: "A", titulo: "Toy Story 5", ano: 2026, genero: "Animação"},
    {tier: "A", titulo: "Jurassic World: Fallen Kingdom", ano: 2018, genero: "Ação / Ficção Científica"},
    {tier: "A", titulo: "Jurassic Park", ano: 1993, genero: "Ação / Ficção Científica"},
    {tier: "A", titulo: "Jurassic Park 2", ano: 1997, genero: "Ação / Ficção Científica"},
    {tier: "A", titulo: "Fast & Furious 5", ano: 2011, genero: "Ação"},
    {tier: "A", titulo: "Fast & Furious 6", ano: 2013, genero: "Ação"},

    // --- TIER B ---
    {tier: "B", titulo: "Peter Pan", ano: 1953, genero: "Animação"},
    {tier: "B", titulo: "101 Dalmatians", ano: 1961, genero: "Animação"},
    {tier: "B", titulo: "Toy Story 2", ano: 1999, genero: "Animação"},
    {tier: "B", titulo: "Lilo & Stitch", ano: 2002, genero: "Animação"},
    {tier: "B", titulo: "Bee Movie", ano: 2007, genero: "Animação"},
    {tier: "B", titulo: "Shrek the Third", ano: 2007, genero: "Animação"},
    {tier: "B", titulo: "Monsters vs. Aliens", ano: 2009, genero: "Animação"},
    {tier: "B", titulo: "Shrek Forever After", ano: 2010, genero: "Animação"},
    {tier: "B", titulo: "Battleship", ano: 2012, genero: "Ação"},
    {tier: "B", titulo: "Annabelle", ano: 2014, genero: "Terror"},
    {tier: "B", titulo: "The Equalizer 2", ano: 2018, genero: "Ação"},
    {tier: "B", titulo: "Captain Marvel", ano: 2019, genero: "Heróis"},
    {tier: "B", titulo: "Thor: Love and Thunder", ano: 2022, genero: "Heróis"},
    {tier: "B", titulo: "Morbius", ano: 2022, genero: "Heróis"},
    {tier: "B", titulo: "Moonfall", ano: 2022, genero: "Drama"},
    {tier: "B", titulo: "Leo", ano: 2023, genero: "Animação"},
    {tier: "B", titulo: "Five Nights at Freddy's 2", ano: 2025, genero: "Terror"},
    {tier: "B", titulo: "Young Washington", ano: 2026, genero: "Ação"},
    {tier: "B", titulo: "Fast & Furious 9", ano: 2021, genero: "Ação"},

    // --- TIER C ---
    {tier: "C", titulo: "The Wolf of Wall Street", ano: 2013, genero: "Drama"},
    {tier: "C", titulo: "Big Hero 6", ano: 2014, genero: "Animação"},
    {tier: "C", titulo: "Deadpool & Wolverine", ano: 2024, genero: "Heróis"},
    {tier: "C", titulo: "Kung Fu Panda 4", ano: 2024, genero: "Animação"},
    {tier: "C", titulo: "Nobody 2", ano: 2025, genero: "Ação"},
    {tier: "C", titulo: "Jurasic world: Rebirth", ano: 2025, genero: "Ação / Ficção Científica"},

    // --- TIER D ---
    {tier: "D", titulo: "Titanic", ano: 1997, genero: "Drama"},
    {tier: "D", titulo: "365 Days", ano: 2020, genero: "Drama"},
    {tier: "D", titulo: "Predador Badlands", ano: 2025, genero: "Ação / Ficção Científica"},
    {tier: "D", titulo: "Sinners", ano: 2025, genero: "Terror"},

    // --- TIER F ---
    {tier: "F", titulo: "Anaconda", ano: 1997, genero: "Terror / Ficção Científica"},
    {tier: "F", titulo: "Anacondas: The Hunt for the Blood Orchid", ano: 2004, genero: "Terror / Ficção Científica"},
    {tier: "F", titulo: "Sharknado", ano: 2013, genero: "Terror / Ficção Científica"},
    {tier: "F", titulo: "Sharknado 2: The Second One", ano: 2014, genero: "Terror / Ficção Científica"},
    {tier: "F", titulo: "365 Days: This Day", ano: 2022, genero: "Drama"},
    {tier: "F", titulo: "The Next 365 Days", ano: 2022, genero: "Drama"},
    {tier: "F", titulo: "The Marvels", ano: 2023, genero: "Heróis"},
    {tier: "F", titulo: "Madame Web", ano: 2024, genero: "Heróis"},
    {tier: "F", titulo: "Wicked", ano: 2024, genero: "Drama"},
    {tier: "F", titulo: "Snow White Live Action", ano: 2025, genero: "Drama"},
    {tier: "F", titulo: "Until Dawn", ano: 2025, genero: "Terror"},
    {tier: "F", titulo: "Harry Potter and the Philosopher's Stone", ano: 2001, genero: "Aventura"}
];