const dadosAnimes = [
    // --- TIER S+ ---
    { tier: "S+", titulo: "Dragon Ball Z", season: "1", ano: 1989 },
    { tier: "S+", titulo: "One Piece", season: "1", ano: 1999 },
    { tier: "S+", titulo: "Naruto", season: "1", ano: 2002 },
    { tier: "S+", titulo: "Death Note", season: "1", ano: 2006 },
    { tier: "S+", titulo: "High School of the Dead", season: "1", ano: 2010 },
    { tier: "S+", titulo: "Another", season: "1", ano: 2012 },
    { tier: "S+", titulo: "Tokyo Ghoul", season: "1", ano: 2014 },
    { tier: "S+", titulo: "One-Punch Man", season: "1", ano: 2015 },
    { tier: "S+", titulo: "Dragon Ball Super", season: "1", ano: 2015 },
    { tier: "S+", titulo: "Cyberpunk: Edgerunners", season: "1", ano: 2022 },
    { tier: "S+", titulo: "Solo Leveling", season: "1", ano: 2024 },
    { tier: "S+", titulo: "Jack-of-All-Trades, Party of None", season: "1", ano: 2024 },
    { tier: "S+", titulo: "Attack on Titan", season: "1, 2", ano: "Mixed" },
    { tier: "S+", titulo: "Frieren: Beyond Journey's End", season: "1, 2", ano: "Mixed" },
    { tier: "S+", titulo: "Hajime no Ippo", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S+", titulo: "Kakegurui", season: "1, 2", ano: "Mixed" },
    { tier: "S+", titulo: "Mushoku Tensei: Jobless Reincarnation", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S+", titulo: "Record of Ragnarok", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S+", titulo: "Shangri-La Frontier", season: "1, 2", ano: "Mixed" },
    { tier: "S+", titulo: "Spy x Family", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S+", titulo: "That Time I Got Reincarnated as a Slime", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S+", titulo: "The Eminence in Shadow", season: "1, 2", ano: "Mixed" },
    { tier: "S+", titulo: "Vinland Saga", season: "1, 2", ano: "Mixed" },

    // --- TIER S ---
    { tier: "S", titulo: "Bleach", season: "1", ano: 2004 },
    { tier: "S", titulo: "Hunter x Hunter", season: "1", ano: 2011 },
    { tier: "S", titulo: "Mirai Nikki", season: "1", ano: 2011 },
    { tier: "S", titulo: "Tokyo Ghoul", season: "2", ano: 2015 },
    { tier: "S", titulo: "Chivalry of a Failed Knight", season: "1", ano: 2015 },
    { tier: "S", titulo: "Attack on Titan", season: "3", ano: 2018 },
    { tier: "S", titulo: "Baki", season: "1, 2", ano: 2018 },
    { tier: "S", titulo: "Wise Man's Grandchild", season: "1", ano: 2019 },
    { tier: "S", titulo: "Jujutsu Kaisen", season: "1", ano: 2020 },
    { tier: "S", titulo: "Tower of God", season: "1", ano: 2020 },
    { tier: "S", titulo: "Tomodachi Game", season: "1", ano: 2022 },
    { tier: "S", titulo: "The Iceblade Sorcerer Shall Rule the World", season: "1", ano: 2023 },
    { tier: "S", titulo: "The Apothecary Diaries", season: "1", ano: 2023 },
    { tier: "S", titulo: "Wand and Sword", season: "1", ano: 2024 },
    { tier: "S", titulo: "I Parry Everything", season: "1", ano: 2024 },
    { tier: "S", titulo: "Wind Breaker", season: "1", ano: 2024 },
    { tier: "S", titulo: "Sakamoto Days", season: "1", ano: 2025 },
    { tier: "S", titulo: "The Water Magician", season: "1", ano: 2025 },
    { tier: "S", titulo: "That Time I Got Reincarnated as a Slime", season: "4", ano: 2026 },
    { tier: "S", titulo: "Baki Hanma: Son of Ogre", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "By the Grace of the Gods", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "Classroom of the Elite", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S", titulo: "Demon Slayer", season: "1, 2, 3, 4", ano: "Mixed" },
    { tier: "S", titulo: "Fairy Tail", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S", titulo: "Fire Force", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "Kaiju No. 8", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "Kuroko's Basketball", season: "1, 2, 3", ano: "Mixed" },
    { tier: "S", titulo: "Mashle: Magic and Muscles", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "My Hero Academia", season: "1, 2, 3, 4, 5, 6, 7", ano: "Mixed" },
    { tier: "S", titulo: "Ranking of Kings", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "Sword Art Online", season: "1, 2", ano: "Mixed" },
    { tier: "S", titulo: "The Seven Deadly Sins", season: "1, 2, 3", ano: "Mixed" },

    // --- TIER A ---
    { tier: "A", titulo: "Elfen Lied", season: "1", ano: 2004 },
    { tier: "A", titulo: "Hellsing Ultimate", season: "1", ano: 2006 },
    { tier: "A", titulo: "Btooom!", season: "1", ano: 2012 },
    { tier: "A", titulo: "Danganronpa: The Animation", season: "1", ano: 2013 },
    { tier: "A", titulo: "No Game No Life", season: "1", ano: 2014 },
    { tier: "A", titulo: "Parasyte", season: "1", ano: 2014 },
    { tier: "A", titulo: "KonoSuba", season: "1", ano: 2016 },
    { tier: "A", titulo: "Sword Art Online Alternative: Gun Gale Online", season: "1", ano: 2018 },
    { tier: "A", titulo: "Grand Blue", season: "1", ano: 2018 },
    { tier: "A", titulo: "Cautious Hero: The Hero Is Overpowered but Overly Cautious", season: "1", ano: 2019 },
    { tier: "A", titulo: "Gleipnir", season: "1", ano: 2020 },
    { tier: "A", titulo: "The World's Finest Assassin Gets Reincarnated in Another World", season: "1", ano: 2021 },
    { tier: "A", titulo: "My Isekai Life", season: "1", ano: 2022 },
    { tier: "A", titulo: "Hell's Paradise", season: "1", ano: 2023 },
    { tier: "A", titulo: "Campfire Cooking in Another World with My Absurd Skill", season: "1", ano: 2023 },
    { tier: "A", titulo: "Dandadan", season: "1", ano: 2024 },
    { tier: "A", titulo: "The Ossan Newbie Adventurer", season: "1", ano: 2024 },
    { tier: "A", titulo: "Classroom of the Elite", season: "4", ano: 2026 },
    { tier: "A", titulo: "Assassination Classroom", season: "1, 2", ano: "Mixed" },
    { tier: "A", titulo: "Haikyu!!", season: "1, 2, 3", ano: "Mixed" },
    { tier: "A", titulo: "The Promised Neverland", season: "1, 2", ano: "Mixed" },

    // --- TIER B ---
    { tier: "B", titulo: "Fullmetal Alchemist: Brotherhood", season: "1", ano: 2009 },
    { tier: "B", titulo: "The Devil Is a Part-Timer!", season: "1", ano: 2013 },
    { tier: "B", titulo: "Akame ga Kill!", season: "1", ano: 2014 },
    { tier: "B", titulo: "Sword Art Online", season: "3", ano: 2018 },
    { tier: "B", titulo: "One-Punch Man", season: "2", ano: 2019 },
    { tier: "B", titulo: "Dr. Stone", season: "1", ano: 2019 },
    { tier: "B", titulo: "Plunderer", season: "1", ano: 2020 },
    { tier: "B", titulo: "Battle Game in 5 Seconds", season: "1", ano: 2021 },
    { tier: "B", titulo: "Blue Lock", season: "1", ano: 2022 },
    { tier: "B", titulo: "Skeleton Knight in Another World", season: "1", ano: 2022 },
    { tier: "B", titulo: "The Wrong Way to Use Healing Magic", season: "1", ano: 2024 },
    { tier: "B", titulo: "Tower of God", season: "2", ano: 2024 },
    { tier: "B", titulo: "The Misfit of Demon King Academy", season: "1, 2", ano: "Mixed" },

    // --- TIER C ---
    { tier: "C", titulo: "Arifureta", season: "1", ano: 2019 },
    { tier: "C", titulo: "Akudama Drive", season: "1", ano: 2020 },
    { tier: "C", titulo: "The Strongest Sage with the Weakest Crest", season: "1", ano: 2022 },
    { tier: "C", titulo: "Hell's Paradise", season: "2", ano: 2026 },

    // --- TIER D ---
    { tier: "D", titulo: "JoJo's Bizarre Adventure", season: "1", ano: 2012 },
    { tier: "D", titulo: "Overlord", season: "1", ano: 2015 },
    { tier: "D", titulo: "The King's Avatar", season: "1", ano: 2017 },
    { tier: "D", titulo: "Bofuri", season: "1", ano: 2020 },
    { tier: "D", titulo: "Tokyo Revengers", season: "1, 2, 3", ano: "Mixed" },

    // --- TIER F ---
    { tier: "F", titulo: "Mob Psycho 100", season: "1", ano: 2016 },
    { tier: "F", titulo: "Berserk", season: "1", ano: 2016 },
    { tier: "F", titulo: "Tokyo Ghoul:re", season: "1", ano: 2018 },
    { tier: "F", titulo: "The Seven Deadly Sins", season: "4", ano: 2021 },
    { tier: "F", titulo: "Black Summoner", season: "1", ano: 2022 },
    { tier: "F", titulo: "Reincarnated as a Sword", season: "1", ano: 2022 },
    { tier: "F", titulo: "The Reincarnation of the Strongest Exorcist in Another World", season: "1", ano: 2023 },
    { tier: "F", titulo: "One-Punch Man", season: "3", ano: 2025 },
    { tier: "F", titulo: "The Beginning After the End", season: "1", ano: 2025 }
];