const dadosJogos = [
            // --- TIER S+ ---
            {tier: "S+", jogo: "Counter-Strike", ano: 2000, plataforma: "Computer"},
            {tier: "S+", jogo: "Call of Duty", ano: 2003, plataforma: "Computer"},
            {tier: "S+", jogo: "The Lord of the Rings: The Return of the King", ano: 2003, plataforma: "Playstation"},
            {tier: "S+", jogo: "Far Cry", ano: 2004, plataforma: "Computer"},
            {tier: "S+", jogo: "Grand Theft Auto: San Andreas", ano: 2004, plataforma: "Computer"},
            {tier: "S+", jogo: "Jak 3", ano: 2004, plataforma: "Playstation"},
            {tier: "S+", jogo: "The Lord of the Rings: The Battle for Middle-earth", ano: 2004, plataforma: "Computer"},
            {tier: "S+", jogo: "God of War (2005)", ano: 2005, plataforma: "Playstation"},
            {tier: "S+", jogo: "Need for Speed Most Wanted", ano: 2005, plataforma: "Playstation"},
            {tier: "S+", jogo: "Project Snowblind", ano: 2005, plataforma: "Computer"},
            {tier: "S+", jogo: "Call of Duty 3", ano: 2006, plataforma: "Computer"},
            {tier: "S+", jogo: "Dead Space Remake", ano: 2023, plataforma: "Computer"},
            {tier: "S+", jogo: "Plants vs. Zombies", ano: 2009, plataforma: "Computer"},
            {tier: "S+", jogo: "Papa's Burgeria", ano: 2010, plataforma: "Computer"},
            {tier: "S+", jogo: "Minecraft", ano: 2011, plataforma: "Computer"},
            {tier: "S+", jogo: "Far Cry 3", ano: 2012, plataforma: "Computer"},
            {tier: "S+", jogo: "Forge of Empires", ano: 2012, plataforma: "Computer"},
            {tier: "S+", jogo: "Banana Kong", ano: 2013, plataforma: "Mobile"},
            {tier: "S+", jogo: "Galaxy Life", ano: 2013, plataforma: "Computer"},
            {tier: "S+", jogo: "Grand Theft Auto V", ano: 2013, plataforma: "Computer"},
            {tier: "S+", jogo: "The Last of Us", ano: 2013, plataforma: "Playstation"},
            {tier: "S+", jogo: "Tomb Raider", ano: 2013, plataforma: "Computer"},
            {tier: "S+", jogo: "Chrome Dino (jogo do dinossauro)", ano: 2014, plataforma: "Computer"},
            {tier: "S+", jogo: "Dino Hunter: Deadly Shores", ano: 2014, plataforma: "Mobile"},
            {tier: "S+", jogo: "Smash Hit", ano: 2014, plataforma: "Mobile"},
            {tier: "S+", jogo: "Agar.io", ano: 2015, plataforma: "Computer"},
            {tier: "S+", jogo: "Dying Light", ano: 2015, plataforma: "Computer"},
            {tier: "S+", jogo: "Until Dawn", ano: 2015, plataforma: "Playstation"},
            {tier: "S+", jogo: "Battlefield 1", ano: 2016, plataforma: "Computer"},
            {tier: "S+", jogo: "Far Cry Primal", ano: 2016, plataforma: "Computer"},
            {tier: "S+", jogo: "Resident Evil 7: Biohazard", ano: 2017, plataforma: "Computer"},
            {tier: "S+", jogo: "Rogue Trooper Redux", ano: 2017, plataforma: "Computer"},
            {tier: "S+", jogo: "Slime Rancher", ano: 2017, plataforma: "Computer"},
            {tier: "S+", jogo: "The Escapists 2", ano: 2017, plataforma: "Computer"},
            {tier: "S+", jogo: "Bloons TD 6", ano: 2018, plataforma: "Computer"},
            {tier: "S+", jogo: "Detroit: Become Human", ano: 2018, plataforma: "Playstation"},
            {tier: "S+", jogo: "God of War", ano: 2018, plataforma: "Playstation"},
            {tier: "S+", jogo: "Not Tonight", ano: 2018, plataforma: "Computer"},
            {tier: "S+", jogo: "Overcooked! 2", ano: 2018, plataforma: "Playstation"},
            {tier: "S+", jogo: "Subnautica", ano: 2018, plataforma: "Computer"},
            {tier: "S+", jogo: "Thief Simulator", ano: 2018, plataforma: "Computer"},
            {tier: "S+", jogo: "A Plague Tale: Innocence", ano: 2019, plataforma: "Computer"},
            {tier: "S+", jogo: "Beat Saber", ano: 2019, plataforma: "Playstation"},
            {tier: "S+", jogo: "Dicey Dungeons", ano: 2019, plataforma: "Computer"},
            {tier: "S+", jogo: "Metro Exodus", ano: 2019, plataforma: "Computer"},
            {tier: "S+", jogo: "Need for Speed Heat", ano: 2019, plataforma: "Playstation"},
            {tier: "S+", jogo: "Totally Accurate Battle Simulator", ano: 2019, plataforma: "Computer"},
            {tier: "S+", jogo: "Cyberpunk 2077", ano: 2020, plataforma: "Computer"},
            {tier: "S+", jogo: "Marvel's Spider-Man: Miles Morales", ano: 2020, plataforma: "Playstation"},
            {tier: "S+", jogo: "Yes, Your Grace", ano: 2020, plataforma: "Computer"},
            {tier: "S+", jogo: "Resident Evil Village", ano: 2021, plataforma: "Computer"},
            {tier: "S+", jogo: "A Plague Tale: Requiem", ano: 2022, plataforma: "Computer"},
            {tier: "S+", jogo: "Grounded", ano: 2022, plataforma: "Computer"},
            {tier: "S+", jogo: "High On Life", ano: 2022, plataforma: "Computer"},
            {tier: "S+", jogo: "Horizon Forbidden West", ano: 2022, plataforma: "Playstation"},
            {tier: "S+", jogo: "Raft", ano: 2022, plataforma: "Computer"},
            {tier: "S+", jogo: "Bronzebeard's Tavern", ano: 2023, plataforma: "Computer"},
            {tier: "S+", jogo: "Contraband Police", ano: 2023, plataforma: "Computer"},
            {tier: "S+", jogo: "Crab Champions", ano: 2023, plataforma: "Computer"},
            {tier: "S+", jogo: "Dave the Diver", ano: 2023, plataforma: "Computer"},
            {tier: "S+", jogo: "Lethal Company", ano: 2023, plataforma: "Computer"},
            {tier: "S+", jogo: "Helldivers II", ano: 2024, plataforma: "Computer"},
            {tier: "S+", jogo: "Stellar Blade", ano: 2024, plataforma: "Playstation"},
            {tier: "S+", jogo: "TCG Card Shop Simulator", ano: 2024, plataforma: "Computer"},
            {tier: "S+", jogo: "Zenless Zone Zero", ano: 2024, plataforma: "Computer"},
            {tier: "S+", jogo: "Schedule I", ano: 2025, plataforma: "Computer"},
            {tier: "S+", jogo: "Resident Evil Requiem", ano: 2026, plataforma: "Computer"},
            // --- TIER S ---
            {tier: "S", jogo: "Jak and Daxter: The Precursor Legacy", ano: 2001, plataforma: "Playstation"},
            {tier: "S", jogo: "Grand Theft Auto: Vice City", ano: 2002, plataforma: "Computer"},
            {tier: "S", jogo: "Jak II", ano: 2003, plataforma: "Playstation"},
            {tier: "S", jogo: "Burnout 3: Takedown", ano: 2004, plataforma: "Playstation"},
            {tier: "S", jogo: "Madagascar", ano: 2005, plataforma: "Playstation"},
            {tier: "S", jogo: "The Lord of the Rings: The Battle for Middle-earth II", ano: 2006, plataforma: "Computer"},
            {tier: "S", jogo: "God of War: Chains of Olympus", ano: 2008, plataforma: "Playstation"},
            {tier: "S", jogo: "Spore", ano: 2008, plataforma: "Computer"},
            {tier: "S", jogo: "The Incredible Hulk", ano: 2008, plataforma: "Playstation"},
            {tier: "S", jogo: "Angry Birds", ano: 2009, plataforma: "Mobile"},
            {tier: "S", jogo: "God of War III", ano: 2010, plataforma: "Playstation"},
            {tier: "S", jogo: "God of War: Ghost of Sparta", ano: 2010, plataforma: "Playstation"},
            {tier: "S", jogo: "Angry Birds Rio", ano: 2011, plataforma: "Mobile"},
            {tier: "S", jogo: "Bloons Tower Defense 5", ano: 2011, plataforma: "Computer"},
            {tier: "S", jogo: "Papa's Freezeria", ano: 2011, plataforma: "Computer"},
            {tier: "S", jogo: "Hungry Shark Evolution", ano: 2012, plataforma: "Mobile"},
            {tier: "S", jogo: "Subway Surfers", ano: 2012, plataforma: "Mobile"},
            {tier: "S", jogo: "Assassin's Creed IV: Black Flag", ano: 2013, plataforma: "Computer"},
            {tier: "S", jogo: "Beyond: Two Souls", ano: 2013, plataforma: "Computer"},
            {tier: "S", jogo: "Dont Touch The Spikes", ano: 2013, plataforma: "Mobile"},
            {tier: "S", jogo: "Far Cry 3: Blood Dragon", ano: 2013, plataforma: "Computer"},
            {tier: "S", jogo: "Earn to Die 2", ano: 2014, plataforma: "Computer"},
            {tier: "S", jogo: "Five Nights at Freddy's", ano: 2014, plataforma: "Computer"},
            {tier: "S", jogo: "Metro 2033 Redux", ano: 2014, plataforma: "Computer"},
            {tier: "S", jogo: "Metro: Last Light Redux", ano: 2014, plataforma: "Computer"},
            {tier: "S", jogo: "Color Switch", ano: 2015, plataforma: "Mobile"},
            {tier: "S", jogo: "Cower Defense", ano: 2015, plataforma: "Computer"},
            {tier: "S", jogo: "Life is Strange", ano: 2015, plataforma: "Playstation"},
            {tier: "S", jogo: "Big Hunter", ano: 2016, plataforma: "Mobile"},
            {tier: "S", jogo: "BioShock 2 Remastered", ano: 2016, plataforma: "Computer"},
            {tier: "S", jogo: "BioShock Remastered", ano: 2016, plataforma: "Computer"},
            {tier: "S", jogo: "Crush the Castle 3 / Adventures", ano: 2016, plataforma: "Computer"},
            {tier: "S", jogo: "Punch Club", ano: 2016, plataforma: "Computer"},
            {tier: "S", jogo: "Superhot", ano: 2016, plataforma: "Computer"},
            {tier: "S", jogo: "Turmoil", ano: 2016, plataforma: "Computer"},
            {tier: "S", jogo: "Cuphead", ano: 2017, plataforma: "Computer"},
            {tier: "S", jogo: "Horizon Zero Dawn", ano: 2017, plataforma: "Playstation"},
            {tier: "S", jogo: "Bad North: Jotunn Edition", ano: 2018, plataforma: "Computer"},
            {tier: "S", jogo: "Battlefield V", ano: 2018, plataforma: "Computer"},
            {tier: "S", jogo: "Paladins", ano: 2018, plataforma: "Computer"},
            {tier: "S", jogo: "Shadow of the Tomb Raider", ano: 2018, plataforma: "Computer"},
            {tier: "S", jogo: "Call of Duty: Modern Warfare", ano: 2019, plataforma: "Computer"},
            {tier: "S", jogo: "Zueirama", ano: 2019, plataforma: "Computer"},
            {tier: "S", jogo: "Crysis (Remastered)", ano: 2020, plataforma: "Computer"},
            {tier: "S", jogo: "Crysis 2 (Remastered)", ano: 2021, plataforma: "Computer"},
            {tier: "S", jogo: "Crysis 3 (Remastered)", ano: 2021, plataforma: "Computer"},
            {tier: "S", jogo: "Hot Wheels Unleashed", ano: 2021, plataforma: "Playstation"},
            {tier: "S", jogo: "It Takes Two", ano: 2021, plataforma: "Playstation"},
            {tier: "S", jogo: "Kena: Bridge of Spirits", ano: 2021, plataforma: "Playstation"},
            {tier: "S", jogo: "Little Nightmares II", ano: 2021, plataforma: "Playstation"},
            {tier: "S", jogo: "Postknight 2", ano: 2021, plataforma: "Mobile"},
            {tier: "S", jogo: "Ratchet & Clank: Rift Apart", ano: 2021, plataforma: "Playstation"},
            {tier: "S", jogo: "Call of Duty: Modern Warfare II", ano: 2022, plataforma: "Computer"},
            {tier: "S", jogo: "God of War Ragnarök", ano: 2022, plataforma: "Playstation"},
            {tier: "S", jogo: "Not Tonight 2", ano: 2022, plataforma: "Computer"},
            {tier: "S", jogo: "Atomic Heart", ano: 2023, plataforma: "Computer"},
            {tier: "S", jogo: "Brotato", ano: 2023, plataforma: "Computer"},
            {tier: "S", jogo: "Dead Island 2", ano: 2023, plataforma: "Computer"},
            {tier: "S", jogo: "Dredge", ano: 2023, plataforma: "Computer"},
            {tier: "S", jogo: "Resident Evil 4 (Remake)", ano: 2023, plataforma: "Computer"},
            {tier: "S", jogo: "Cronos: The New Dawn", ano: 2025, plataforma: "Computer"},
            {tier: "S", jogo: "MOUSE: P.I. for Hire", ano: 2025, plataforma: "Computer"},
            {tier: "S", jogo: "Pragmata", ano: 2026, plataforma: "Computer"},
            {tier: "S", jogo: "Quarantine Zone: The Last Check", ano: 2026, plataforma: "Computer"},
            // --- TIER A ---
            {tier: "A", jogo: "Finding Nemo", ano: 2003, plataforma: "Computer"},
            {tier: "A", jogo: "Terrorist Takedown", ano: 2004, plataforma: "Computer"},
            {tier: "A", jogo: "Call of Duty 2", ano: 2005, plataforma: "Computer"},
            {tier: "A", jogo: "Tekken 5", ano: 2005, plataforma: "Playstation"},
            {tier: "A", jogo: "Ice Age 2: The Meltdown", ano: 2006, plataforma: "Computer"},
            {tier: "A", jogo: "Raft Wars", ano: 2007, plataforma: "Computer"},
            {tier: "A", jogo: "Need for Speed Undercover", ano: 2008, plataforma: "Computer"},
            {tier: "A", jogo: "Bloons Tower Defense 4", ano: 2009, plataforma: "Computer"},
            {tier: "A", jogo: "Crush the Castle", ano: 2009, plataforma: "Computer"},
            {tier: "A", jogo: "Crush the Castle 2", ano: 2010, plataforma: "Computer"},
            {tier: "A", jogo: "Cut the Rope", ano: 2010, plataforma: "Mobile"},
            {tier: "A", jogo: "Happy Wheels", ano: 2010, plataforma: "Computer"},
            {tier: "A", jogo: "Snail Bob", ano: 2010, plataforma: "Computer"},
            {tier: "A", jogo: "Defend Your Nuts", ano: 2011, plataforma: "Computer"},
            {tier: "A", jogo: "Rock of Ages", ano: 2011, plataforma: "Computer"},
            {tier: "A", jogo: "Binary Domain", ano: 2012, plataforma: "Computer"},
            {tier: "A", jogo: "Earn to Die", ano: 2012, plataforma: "Computer"},
            {tier: "A", jogo: "Plants vs. Zombies 2", ano: 2013, plataforma: "Mobile"},
            {tier: "A", jogo: "Cow Evolution", ano: 2014, plataforma: "Mobile"},
            {tier: "A", jogo: "Far Cry 4", ano: 2014, plataforma: "Computer"},
            {tier: "A", jogo: "Five Nights at Freddy's 2", ano: 2014, plataforma: "Computer"},
            {tier: "A", jogo: "Tasty Blue", ano: 2014, plataforma: "Computer"},
            {tier: "A", jogo: "Rise of the Tomb Raider", ano: 2015, plataforma: "Computer"},
            {tier: "A", jogo: "Rocket League", ano: 2015, plataforma: "Playstation"},
            {tier: "A", jogo: "Call of Duty: Infinite Warfare", ano: 2016, plataforma: "Computer"},
            {tier: "A", jogo: "ClusterTruck", ano: 2016, plataforma: "Computer"},
            {tier: "A", jogo: "Diep.io", ano: 2016, plataforma: "Computer"},
            {tier: "A", jogo: "Doom (2016)", ano: 2016, plataforma: "Computer"},
            {tier: "A", jogo: "Five Nights at Freddy's: Sister Location", ano: 2016, plataforma: "Computer"},
            {tier: "A", jogo: "Hungry Shark World", ano: 2016, plataforma: "Mobile"},
            {tier: "A", jogo: "Plague Inc: Evolved", ano: 2016, plataforma: "Mobile"},
            {tier: "A", jogo: "Poly Bridge", ano: 2016, plataforma: "Computer"},
            {tier: "A", jogo: "Fortnite", ano: 2017, plataforma: "Computer"},
            {tier: "A", jogo: "Hellblade: Senua's Sacrifice", ano: 2017, plataforma: "Playstation"},
            {tier: "A", jogo: "Little Nightmares", ano: 2017, plataforma: "Playstation"},
            {tier: "A", jogo: "Outlast 2", ano: 2017, plataforma: "Computer"},
            {tier: "A", jogo: "Postknight", ano: 2017, plataforma: "Mobile"},
            {tier: "A", jogo: "Rock of Ages II: Bigger & Boulder", ano: 2017, plataforma: "Computer"},
            {tier: "A", jogo: "Life is Strange 2", ano: 2018, plataforma: "Playstation"},
            {tier: "A", jogo: "Marvel's Spider-Man", ano: 2018, plataforma: "Playstation"},
            {tier: "A", jogo: "Red Dead Redemption II", ano: 2018, plataforma: "Computer"},
            {tier: "A", jogo: "Internet Cafe Simulator", ano: 2019, plataforma: "Computer"},
            {tier: "A", jogo: "Jump Force", ano: 2019, plataforma: "Playstation"},
            {tier: "A", jogo: "Resident Evil 2 (Remake)", ano: 2019, plataforma: "Computer"},
            {tier: "A", jogo: "The Walking Dead: The Telltale Definitive Series", ano: 2019, plataforma: "Playstation"},
            {tier: "A", jogo: "Untitled Goose Game", ano: 2019, plataforma: "Playstation"},
            {tier: "A", jogo: "Alba: A Wildlife Adventure", ano: 2020, plataforma: "Playstation"},
            {tier: "A", jogo: "Astro's Playroom", ano: 2020, plataforma: "Playstation"},
            {tier: "A", jogo: "Biped", ano: 2020, plataforma: "Playstation"},
            {tier: "A", jogo: "Doom Eternal", ano: 2020, plataforma: "Computer"},
            {tier: "A", jogo: "Journey to the Savage Planet", ano: 2020, plataforma: "Computer"},
            {tier: "A", jogo: "Laser Quest", ano: 2020, plataforma: "Mobile"},
            {tier: "A", jogo: "Resident Evil 3 (Remake)", ano: 2020, plataforma: "Computer"},
            {tier: "A", jogo: "Rock of Ages 3: Make & Break", ano: 2020, plataforma: "Computer"},
            {tier: "A", jogo: "Sackboy: A Big Adventure", ano: 2020, plataforma: "Playstation"},
            {tier: "A", jogo: "The Last of Us Part II", ano: 2020, plataforma: "Playstation"},
            {tier: "A", jogo: "Demon Slayer: Kimetsu no Yaiba", ano: 2021, plataforma: "Playstation"},
            {tier: "A", jogo: "Subnautica: Below Zero", ano: 2021, plataforma: "Computer"},
            {tier: "A", jogo: "Endling: Extinction is Forever", ano: 2022, plataforma: "Playstation"},
            {tier: "A", jogo: "Internet Cafe Simulator 2", ano: 2022, plataforma: "Computer"},
            {tier: "A", jogo: "Alan Wake II", ano: 2023, plataforma: "Playstation"},
            {tier: "A", jogo: "Lies of P", ano: 2023, plataforma: "Playstation"},
            {tier: "A", jogo: "Thief Simulator 2", ano: 2023, plataforma: "Computer"},
            {tier: "A", jogo: "Supermarket Simulator", ano: 2024, plataforma: "Computer"},
            {tier: "A", jogo: "Truck Loader", ano: 2024, plataforma: "Computer"},
            {tier: "A", jogo: "Archero 2", ano: 2025, plataforma: "Mobile"},
            {tier: "A", jogo: "Clair Obscur: Expedition 33", ano: 2025, plataforma: "Playstation"},
            {tier: "A", jogo: "Dying Light: The Beast", ano: 2025, plataforma: "Computer"},
            {tier: "A", jogo: "FEROCIOUS", ano: 2025, plataforma: "Computer"},
            {tier: "A", jogo: "South of Midnight", ano: 2025, plataforma: "Playstation"},
            {tier: "A", jogo: "The Bazaar", ano: 2025, plataforma: "Computer"},
            {tier: "A", jogo: "Horsey Game", ano: 2026, plataforma: "Computer"},
            {tier: "A", jogo: "Moonlighter 2: The Endless Vault", ano: 2026, plataforma: "Computer"},
            // --- TIER B ---
            {tier: "B", jogo: "Battlefield Vietnam", ano: 2004, plataforma: "Computer"},
            {tier: "B", jogo: "Sniper Elite", ano: 2005, plataforma: "Computer"},
            {tier: "B", jogo: "Papa Louie: When Pizza Attacks!", ano: 2006, plataforma: "Computer"},
            {tier: "B", jogo: "God of War II", ano: 2007, plataforma: "Playstation"},
            {tier: "B", jogo: "Marine Sharpshooter 3", ano: 2007, plataforma: "Computer"},
            {tier: "B", jogo: "Bloons Tower Defense 2", ano: 2007, plataforma: "Computer"},
            {tier: "B", jogo: "Grand Theft Auto IV", ano: 2008, plataforma: "Computer"},
            {tier: "B", jogo: "Fireboy and Watergirl", ano: 2009, plataforma: "Computer"},
            {tier: "B", jogo: "Penguin Diner", ano: 2009, plataforma: "Computer"},
            {tier: "B", jogo: "8 Ball Pool", ano: 2010, plataforma: "Computer"},
            {tier: "B", jogo: "Penguin Diner 2", ano: 2010, plataforma: "Computer"},
            {tier: "B", jogo: "Kingdom Rush", ano: 2011, plataforma: "Computer"},
            {tier: "B", jogo: "Candy Crush Saga", ano: 2012, plataforma: "Mobile"},
            {tier: "B", jogo: "Little Inferno", ano: 2012, plataforma: "Computer"},
            {tier: "B", jogo: "Papa's Pancakeria", ano: 2012, plataforma: "Computer"},
            {tier: "B", jogo: "Zombie Tsunami", ano: 2012, plataforma: "Mobile"},
            {tier: "B", jogo: "BioShock Infinite", ano: 2013, plataforma: "Computer"},
            {tier: "B", jogo: "Company of Heroes 2", ano: 2013, plataforma: "Computer"},
            {tier: "B", jogo: "Raft Wars 2", ano: 2013, plataforma: "Computer"},
            {tier: "B", jogo: "The Sims 4", ano: 2014, plataforma: "Computer"},
            {tier: "B", jogo: "Zombie Night Terror", ano: 2016, plataforma: "Computer"},
            {tier: "B", jogo: "Getting Over It", ano: 2017, plataforma: "Computer"},
            {tier: "B", jogo: "Star Wars: Battlefront II", ano: 2017, plataforma: "Computer"},
            {tier: "B", jogo: "Circle Empires", ano: 2018, plataforma: "Computer"},
            {tier: "B", jogo: "Far Cry 5", ano: 2018, plataforma: "Computer"},
            {tier: "B", jogo: "Graveyard Keeper", ano: 2018, plataforma: "Computer"},
            {tier: "B", jogo: "The Bard's Tale ARPG", ano: 2018, plataforma: "Playstation"},
            {tier: "B", jogo: "60 Seconds! Reatomized", ano: 2019, plataforma: "Computer"},
            {tier: "B", jogo: "Decay of Logos", ano: 2019, plataforma: "Computer"},
            {tier: "B", jogo: "Ice Age: Scrat's Nutty Adventure", ano: 2019, plataforma: "Playstation"},
            {tier: "B", jogo: "Mortal Kombat 11", ano: 2019, plataforma: "Playstation"},
            {tier: "B", jogo: "The Dark Pictures Anthology: Man of Medan", ano: 2019, plataforma: "Playstation"},
            {tier: "B", jogo: "Industria", ano: 2021, plataforma: "Computer"},
            {tier: "B", jogo: "Jurassic World Evolution 2", ano: 2021, plataforma: "Computer"},
            {tier: "B", jogo: "Marsupilami: Hoobadventure", ano: 2021, plataforma: "Playstation"},
            {tier: "B", jogo: "Poppy Playtime", ano: 2021, plataforma: "Computer"},
            {tier: "B", jogo: "Tunic", ano: 2022, plataforma: "Computer"},
            {tier: "B", jogo: "100 Asian Cats", ano: 2023, plataforma: "Computer"},
            {tier: "B", jogo: "Viewfinder", ano: 2023, plataforma: "Computer"},
            {tier: "B", jogo: "Backrooms Society", ano: 2024, plataforma: "Computer"},
            {tier: "B", jogo: "Capybara Go!", ano: 2024, plataforma: "Mobile"},
            {tier: "B", jogo: "Sketchy's Contract", ano: 2024, plataforma: "Computer"},
            {tier: "B", jogo: "The Plucky Squire", ano: 2024, plataforma: "Computer"},
            // --- TIER C ---
            {tier: "C", jogo: "Bloons Tower Defense", ano: 2007, plataforma: "Computer"},
            {tier: "C", jogo: "Fruit Ninja", ano: 2010, plataforma: "Mobile"},
            {tier: "C", jogo: "Home Sheep Home", ano: 2010, plataforma: "Computer"},
            {tier: "C", jogo: "Shaun the Sheep: Beauty Baahn", ano: 2010, plataforma: "Computer"},
            {tier: "C", jogo: "Sushi Cat", ano: 2010, plataforma: "Computer"},
            {tier: "C", jogo: "Transformice", ano: 2010, plataforma: "Computer"},
            {tier: "C", jogo: "Jetpack Joyride", ano: 2011, plataforma: "Mobile"},
            {tier: "C", jogo: "Cookie Clicker", ano: 2013, plataforma: "Computer"},
            {tier: "C", jogo: "Crossy Road", ano: 2014, plataforma: "Playstation"},
            {tier: "C", jogo: "Overwatch", ano: 2016, plataforma: "Computer"},
            {tier: "C", jogo: "Slither.io", ano: 2016, plataforma: "Computer"},
            {tier: "C", jogo: "911 Operator", ano: 2017, plataforma: "Computer"},
            {tier: "C", jogo: "Alan Wake Remastered", ano: 2021, plataforma: "Playstation"},
            {tier: "C", jogo: "Inscryption", ano: 2021, plataforma: "Computer"},
            {tier: "C", jogo: "Super Auto Pets", ano: 2021, plataforma: "Computer"},
            {tier: "C", jogo: "Swamp Attack 2", ano: 2021, plataforma: "Mobile"},
            {tier: "C", jogo: "Webbed", ano: 2021, plataforma: "Computer"},
            {tier: "C", jogo: "Vampire Survivors", ano: 2022, plataforma: "Computer"},
            {tier: "C", jogo: "Above Snakes", ano: 2023, plataforma: "Computer"},
            {tier: "C", jogo: "Pizza Possum", ano: 2023, plataforma: "Computer"},
            {tier: "C", jogo: "Terra Nil", ano: 2023, plataforma: "Computer"},
            {tier: "C", jogo: "Buckshot Roulette", ano: 2024, plataforma: "Computer"},
            {tier: "C", jogo: "Flat Fat Fartfest", ano: 2024, plataforma: "Computer"},
            {tier: "C", jogo: "DOOM: The Dark Ages", ano: 2025, plataforma: "Computer"},
            {tier: "C", jogo: "Kingshot", ano: 2025, plataforma: "Mobile"},
            {tier: "C", jogo: "Replaced", ano: 2026, plataforma: "Computer"},
            // --- TIER D ---
            {tier: "D", jogo: "Fancy Pants Adventure", ano: 2006, plataforma: "Computer"},
            {tier: "D", jogo: "Bloons Tower Defense 3", ano: 2008, plataforma: "Computer"},
            {tier: "D", jogo: "Terraria", ano: 2011, plataforma: "Computer"},
            {tier: "D", jogo: "Clash of Clans", ano: 2012, plataforma: "Mobile"},
            {tier: "D", jogo: "Geometry Dash", ano: 2013, plataforma: "Mobile"},
            {tier: "D", jogo: "Outlast", ano: 2013, plataforma: "Computer"},
            {tier: "D", jogo: "Clash Royale", ano: 2016, plataforma: "Mobile"},
            {tier: "D", jogo: "Life is Strange: Before the Storm", ano: 2017, plataforma: "Playstation"},
            {tier: "D", jogo: "Castle Break", ano: 2019, plataforma: "Computer"},
            {tier: "D", jogo: "Ghost of Tsushima", ano: 2020, plataforma: "Playstation"},
            {tier: "D", jogo: "Maneater", ano: 2020, plataforma: "Playstation"},
            {tier: "D", jogo: "The Dark Pictures Anthology: Little Hope", ano: 2020, plataforma: "Playstation"},
            {tier: "D", jogo: "Breathedge", ano: 2021, plataforma: "Computer"},
            {tier: "D", jogo: "Banana Kong 2", ano: 2022, plataforma: "Mobile"},
            {tier: "D", jogo: "Let's Go Party", ano: 2022, plataforma: "Computer"},
            {tier: "D", jogo: "Deducto", ano: 2023, plataforma: "Computer"},
            {tier: "D", jogo: "Tales of Kenzera: ZAU", ano: 2024, plataforma: "Playstation"},
            // --- TIER F ---
            {tier: "F", jogo: "Roblox", ano: 2006, plataforma: "Computer"},
            {tier: "F", jogo: "Far Cry 2", ano: 2008, plataforma: "Computer"},
            {tier: "F", jogo: "League of Legends", ano: 2009, plataforma: "Computer"},
            {tier: "F", jogo: "Limbo", ano: 2010, plataforma: "Computer"},
            {tier: "F", jogo: "Papers, Please", ano: 2013, plataforma: "Computer"},
            {tier: "F", jogo: "Angry Birds 2", ano: 2015, plataforma: "Mobile"},
            {tier: "F", jogo: "Batman: Arkham Knight", ano: 2015, plataforma: "Computer"},
            {tier: "F", jogo: "Five Nights at Freddy's 3", ano: 2015, plataforma: "Computer"},
            {tier: "F", jogo: "Rainbow Six Siege", ano: 2015, plataforma: "Computer"},
            {tier: "F", jogo: "Dead by Daylight", ano: 2016, plataforma: "Computer"},
            {tier: "F", jogo: "Deus Ex: Mankind Divided", ano: 2016, plataforma: "Computer"},
            {tier: "F", jogo: "Firewatch", ano: 2016, plataforma: "Computer"},
            {tier: "F", jogo: "Titanfall 2", ano: 2016, plataforma: "Computer"},
            {tier: "F", jogo: "Uncharted 4: A Thief's End", ano: 2016, plataforma: "Playstation"},
            {tier: "F", jogo: "Unravel", ano: 2016, plataforma: "Playstation"},
            {tier: "F", jogo: "Greedy Guns", ano: 2017, plataforma: "Computer"},
            {tier: "F", jogo: "Bouncemasters", ano: 2018, plataforma: "Mobile"},
            {tier: "F", jogo: "Apex Legends", ano: 2019, plataforma: "Computer"},
            {tier: "F", jogo: "Blazing Beaks", ano: 2019, plataforma: "Computer"},
            {tier: "F", jogo: "Far Cry New Dawn", ano: 2019, plataforma: "Computer"},
            {tier: "F", jogo: "One Piece World Seeker", ano: 2019, plataforma: "Playstation"},
            {tier: "F", jogo: "Star Wars Jedi: Fallen Order", ano: 2019, plataforma: "Playstation"},
            {tier: "F", jogo: "Valorant", ano: 2020, plataforma: "Computer"},
            {tier: "F", jogo: "Far Cry 6", ano: 2021, plataforma: "Computer"},
            {tier: "F", jogo: "Five Nights at Freddy's: Security Breach", ano: 2021, plataforma: "Computer"},
            {tier: "F", jogo: "Overwatch 2", ano: 2022, plataforma: "Computer"},
            {tier: "F", jogo: "The Callisto Protocol", ano: 2022, plataforma: "Computer"},
            {tier: "F", jogo: "The Quarry", ano: 2022, plataforma: "Playstation"},
            {tier: "F", jogo: "Counter-Strike 2", ano: 2023, plataforma: "Computer"},
            {tier: "F", jogo: "Forspoken", ano: 2023, plataforma: "Playstation"},
            {tier: "F", jogo: "Hi-Fi Rush", ano: 2023, plataforma: "Computer"},
            {tier: "F", jogo: "Punch Club 2: Fast Forward", ano: 2023, plataforma: "Computer"},
            {tier: "F", jogo: "The Demonologist", ano: 2023, plataforma: "Computer"},
            {tier: "F", jogo: "Content Warning", ano: 2024, plataforma: "Computer"},
            {tier: "F", jogo: "Silent Hill 2 Remake", ano: 2024, plataforma: "Computer"},
            {tier: "F", jogo: "Atomfall", ano: 2025, plataforma: "Computer"},
            {tier: "F", jogo: "Halo: Campaign Evolved", ano: 2026, plataforma: "Computer"},
        ];