const dadosSeries = [
            // --- TIER S+ ---
            {tier: "S+", titulo: "The Walking Dead", season: "1", ano: 2010, genero: "Action"},
            {tier: "S+", titulo: "The Witcher", season: "1", ano: 2019, genero: "Adventure"},
            {tier: "S+", titulo: "Primal", season: "1", ano: 2019, genero: "Animation"},
            {tier: "S+", titulo: "The Queen's Gambit", season: "1", ano: 2020, genero: "Drama"},
            {tier: "S+", titulo: "Wednesday", season: "1", ano: 2022, genero: "Mystery"},
            {tier: "S+", titulo: "All of Us Are Dead", season: "1", ano: 2022, genero: "Japanese"},
            {tier: "S+", titulo: "Weak Hero", season: "1", ano: 2022, genero: "Japanese"},
            {tier: "S+", titulo: "Fallout", season: "2", ano: 2025, genero: "Action"},
            {tier: "S+", titulo: "Teach You a Lesson", season: "1", ano: 2026, genero: "Japanese"},
            {tier: "S+", titulo: "Alice in Borderland", season: "1, 2", ano: "Mixed", genero: "Japanese"},
            {tier: "S+", titulo: "Arcane", season: "1, 2", ano: "Mixed", genero: "Animation"},
            {tier: "S+", titulo: "Bloodhounds", season: "1, 2", ano: "Mixed", genero: "Japanese"},
            {tier: "S+", titulo: "Game of Thrones", season: "1, 2, 3, 4, 5, 6", ano: "Mixed", genero: "Adventure"},
            {tier: "S+", titulo: "La Casa de Papel", season: "1, 2, 3, 4, 5", ano: "Mixed", genero: "Action"},
            {tier: "S+", titulo: "Locke & Key", season: "1, 2", ano: "Mixed", genero: "Mystery"},
            {tier: "S+", titulo: "Loki", season: "1, 2", ano: "Mixed", genero: "Action"},
            {tier: "S+", titulo: "One piece", season: "1, 2", ano: "Mixed", genero: "Adventure"},
            {tier: "S+", titulo: "Peaky Blinders", season: "1, 3, 4", ano: "Mixed", genero: "Action"},
            {tier: "S+", titulo: "Regular Show", season: "1, 2, 3, 4, 5, 6, 7, 8", ano: "Mixed", genero: "Animation"},
            {tier: "S+", titulo: "Sex Education", season: "1, 2", ano: "Mixed", genero: "Comedy"},
            {tier: "S+", titulo: "Squid Game", season: "1, 2", ano: "Mixed", genero: "Japanese"},
            {tier: "S+", titulo: "Stranger Things", season: "1, 2, 4, 5", ano: "Mixed", genero: "Action"},
            {tier: "S+", titulo: "The Amazing World of Gumball", season: "1, 2, 3, 4, 5, 6", ano: "Mixed", genero: "Animation"},
            {tier: "S+", titulo: "The Punisher", season: "1, 2", ano: "Mixed", genero: "Action"},
            // --- TIER S ---
            {tier: "S", titulo: "The Walking Dead", season: "2", ano: 2011, genero: "Action"},
            {tier: "S", titulo: "Vikings", season: "1", ano: 2013, genero: "Adventure"},
            {tier: "S", titulo: "Game of Thrones", season: "7", ano: 2017, genero: "Adventure"},
            {tier: "S", titulo: "Stranger Things", season: "3", ano: 2019, genero: "Action"},
            {tier: "S", titulo: "House of the Dragon", season: "1", ano: 2022, genero: "Adventure"},
            {tier: "S", titulo: "The Last of Us", season: "1", ano: 2023, genero: "Action"},
            {tier: "S", titulo: "Fallout", season: "1", ano: 2024, genero: "Action"},
            {tier: "S", titulo: "Shōgun", season: "1", ano: 2024, genero: "Adventure"},
            {tier: "S", titulo: "Wednesday", season: "2", ano: 2025, genero: "Mystery"},
            {tier: "S", titulo: "Halo", season: "1, 2", ano: "Mixed", genero: "Action"},
            {tier: "S", titulo: "Peaky Blinders", season: "2, 5, 6", ano: "Mixed", genero: "Action"},
            {tier: "S", titulo: "Reacher", season: "1, 2", ano: "Mixed", genero: "Action"},
            {tier: "S", titulo: "Sex Education", season: "3, 4", ano: "Mixed", genero: "Comedy"},
            {tier: "S", titulo: "The Mandalorian", season: "1, 2", ano: "Mixed", genero: "Adventure"},
            {tier: "S", titulo: "The Witcher", season: "2, 3", ano: "Mixed", genero: "Adventure"},
            // --- TIER A ---
            {tier: "A", titulo: "Vikings", season: "2", ano: 2014, genero: "Adventure"},
            {tier: "A", titulo: "Locke & Key", season: "3", ano: 2022, genero: "Mystery"},
            {tier: "A", titulo: "From", season: "1", ano: 2022, genero: "Mystery"},
            {tier: "A", titulo: "The Mandalorian", season: "3", ano: 2023, genero: "Adventure"},
            {tier: "A", titulo: "Knuckles", season: "1", ano: 2024, genero: "Action"},
            {tier: "A", titulo: "The Last of Us", season: "2", ano: 2025, genero: "Action"},
            {tier: "A", titulo: "The Witcher", season: "4", ano: 2025, genero: "Adventure"},
            {tier: "A", titulo: "Rick and Morty", season: "1, 2, 3, 4, 5, 6, 7", ano: "Mixed", genero: "Animation"},
            {tier: "A", titulo: "The Good Doctor", season: "1, 2, 3, 4, 5, 6", ano: "Mixed", genero: "Drama"},
            // --- TIER B ---
            {tier: "B", titulo: "The Walking Dead", season: "3", ano: 2012, genero: "Action"},
            {tier: "B", titulo: "Game of Thrones", season: "8", ano: 2019, genero: "Adventure"},
        ];